# Numpy Introduction

In [12]:
import numpy as np

In [16]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
a2 = a[np.newaxis, :]
print(a2)
a2.shape

[[0 1 2 3 4 5 6 7 8 9]]


(1, 10)

In [20]:
a2 = a[: , np.newaxis]
print(a2)
a2.shape

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


(10, 1)